
version: "3"

services:
  squid:
    image: pxsrv
    ports:
      - "5000:5000"
    volumes:
      - ./cert:/etc/docker-proxy/cert
    restart: always
  
  squidxnc:
    image: pxsrv
    ports:
      - "6000:5000"
    volumes:
      - ./cert:/etc/docker-proxy/cert
    restart: always


 
  
   
